title: Innit  
author: Innit
email: 
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: 
github_username: 

sass:
    style: compressed

include: ["_pages",]
permalink: /:title/
